### ISSUE TITLE
    kotlin.UninitializedPropertyAccessException: lateinit property _binding has not been initialized

### ISSUE THREAD

**Issue by TasarimSepeti** [D4rK7355608/com.d4rk.qrcodescanner.plus#14]
E/AndroidRuntime: FATAL EXCEPTION: main
    kotlin.UninitializedPropertyAccessException: lateinit property _binding has not been initialized
        at qrcode.barcode.scannerandreader.feature.common.dialog.EditBarcodeNameDialogFragment.getBinding(EditBarcodeNameDialogFragment.kt:15)
        at qrcode.barcode.scannerandreader.feature.common.dialog.EditBarcodeNameDialogFragment.onCreateDialog$lambda-1(EditBarcodeNameDialogFragment.kt:39)
        at qrcode.barcode.scannerandreader.feature.common.dialog.EditBarcodeNameDialogFragment.$r8$lambda$dal_yMtdz2vz4MA2HUtFmqFSjX4(Unknown Source:0)
        at qrcode.barcode.scannerandreader.feature.common.dialog.EditBarcodeNameDialogFragment$$ExternalSyntheticLambda1.onShow(Unknown Source:6)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1443)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8301)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)

**Comment by D4rK7355608** [comment]
We appreciate you sharing the logs with us. The issue has been resolved. A major update, including a new layout, additional settings, and bug fixes, is on its way. Thank you for your patience!
