### ISSUE TITLE
Crash when tapping on "choose another image"

### ISSUE THREAD

**Issue by NikunjKhangwal** [D4rK7355608/com.d4rk.qrcodescanner.plus#21]
**Here's the crash log**

FATAL EXCEPTION: main
Process: com.d4rk.qrcodescanner.plus, PID: 29794
java.lang.IllegalStateException: LifecycleOwner com.d4rk.qrcodescanner.plus.ui.scan.file.ScanBarcodeFromFileActivity@9610bee is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
	at androidx.activity.result.h.c(Unknown Source:93)
	at com.d4rk.qrcodescanner.plus.ui.scan.file.ScanBarcodeFromFileActivity.C(Unknown Source:34)
	at com.d4rk.qrcodescanner.plus.ui.scan.file.ScanBarcodeFromFileActivity.onOptionsItemSelected(Unknown Source:59)
	at android.app.Activity.onMenuItemSelected(Activity.java:4418)
	at androidx.activity.l.onMenuItemSelected(Unknown Source:0)
	at androidx.fragment.app.c0.onMenuItemSelected(Unknown Source:0)
	at e.o.onMenuItemSelected(Unknown Source:0)
	at e.d0.n(Unknown Source:2)
	at e.d0.onMenuItemSelected(Unknown Source:0)
	at e.j0.h(Unknown Source:43)
	at i.o.e(Unknown Source:4)
	at i.o.q(Unknown Source:27)
	at androidx.appcompat.widget.ActionMenuView.d(Unknown Source:4)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7751)
	at android.view.View.performClickInternal(View.java:7724)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29332)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by Starcr0ss** [comment]
Similar to your issue, if I import an already taken image using the share menu or "Scan image" feature, I get a popup box that says "Error: Something went wrong" and it pops up constantly if I try to crop/move the selection of the image. This breaks a core functionality of the app: Getting QR codes from local images (as opposed to the camera)
